#!/bin/bash
#
# Run Full-Stack Test Protocol
#
# Usage:
#   ./scripts/run-test-protocol.sh [OPTIONS]
#
# Options:
#   --suite SUITE    Test suite to run: preflight, core, stretch, all (default: core)
#   --output DIR     Output directory for results (default: docs/test-results)
#   --model MODEL    Model to use: sonnet, opus (default: sonnet)
#   --help           Show this help message
#
# Prerequisites:
#   - Claude Code CLI installed and authenticated
#   - KOI MCP configured
#   - Go 1.22+ (for NU-01)
#   - Rust + wasm32 target (for SC-01)
#   - Python 3.11+ (for VC-01, CA-01)

set -e

# Defaults
SUITE="core"
OUTPUT_DIR="docs/test-results"
MODEL="sonnet"
TIMESTAMP=$(date +%Y-%m-%d-%H%M)
RESULTS_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --suite)
            SUITE="$2"
            shift 2
            ;;
        --output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --model)
            MODEL="$2"
            shift 2
            ;;
        --help)
            head -25 "$0" | tail -20
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Create output directory
mkdir -p "$OUTPUT_DIR"
RESULTS_FILE="$OUTPUT_DIR/${TIMESTAMP}-manual.md"

echo "================================"
echo "Full-Stack Test Protocol Runner"
echo "================================"
echo "Suite: $SUITE"
echo "Model: $MODEL"
echo "Output: $RESULTS_FILE"
echo "================================"
echo ""

# Environment check
echo "=== Environment Check ==="
check_tool() {
    local name=$1
    local cmd=$2
    local required=$3

    if command -v $cmd &> /dev/null; then
        echo "  [OK] $name: $($cmd --version 2>&1 | head -1)"
        return 0
    else
        if [ "$required" == "required" ]; then
            echo "  [FAIL] $name: NOT INSTALLED (required)"
            return 1
        else
            echo "  [WARN] $name: not installed (optional for some tests)"
            return 0
        fi
    fi
}

ENV_OK=true
check_tool "Python" "python3" "required" || ENV_OK=false
check_tool "Go" "go" "optional"
check_tool "Rust" "rustc" "optional"
check_tool "Cargo" "cargo" "optional"
check_tool "Node.js" "node" "optional"

if [ "$ENV_OK" == "false" ]; then
    echo ""
    echo "ERROR: Required tools missing. Cannot continue."
    exit 1
fi

echo ""

# Initialize results file
cat > "$RESULTS_FILE" << EOF
# Test Results - $TIMESTAMP

**Date:** $(date)
**Suite:** $SUITE
**Model:** $MODEL
**Runner:** Manual ($(whoami)@$(hostname))

---

## Environment

| Tool | Version | Status |
|------|---------|--------|
| Python | $(python3 --version 2>&1 | cut -d' ' -f2) | OK |
| Go | $(go version 2>&1 | cut -d' ' -f3 || echo "N/A") | $(command -v go &>/dev/null && echo "OK" || echo "Missing") |
| Rust | $(rustc --version 2>&1 | cut -d' ' -f2 || echo "N/A") | $(command -v rustc &>/dev/null && echo "OK" || echo "Missing") |
| Node | $(node --version 2>&1 || echo "N/A") | $(command -v node &>/dev/null && echo "OK" || echo "Missing") |

---

EOF

# Test definitions
run_test() {
    local test_id=$1
    local test_name=$2
    local prompt_file=$3

    echo "=== Running $test_id: $test_name ==="

    # For now, just log that we would run the test
    # Actual implementation would invoke Claude Code CLI

    cat >> "$RESULTS_FILE" << EOF
## $test_id: $test_name

**Status:** Pending manual execution
**Prompt:** See docs/test-protocol-full-stack.md

---

EOF

    echo "  -> Logged to results file (manual execution required)"
    echo ""
}

# Run tests based on suite
if [ "$SUITE" == "preflight" ] || [ "$SUITE" == "core" ] || [ "$SUITE" == "all" ]; then
    echo "=== Preflight Check ==="
    echo "Run the preflight prompt from docs/test-protocol-full-stack.md"
    echo ""
fi

if [ "$SUITE" == "core" ] || [ "$SUITE" == "all" ]; then
    run_test "VC-01" "Small feature + unit tests" "prompts/vc-01.txt"
    run_test "VC-02" "Fix a real integration mismatch" "prompts/vc-02.txt"
    run_test "NU-01" "Add upgrade handler scaffold" "prompts/nu-01.txt"
    run_test "SC-01" "Generate minimal CosmWasm contract" "prompts/sc-01.txt"
    run_test "CA-01" "Basket token helper mini-app" "prompts/ca-01.txt"
fi

if [ "$SUITE" == "stretch" ] || [ "$SUITE" == "all" ]; then
    run_test "NU-02" "Upgrade planning from docs" "prompts/nu-02.txt"
    run_test "SC-02" "Deploy to local chain" "prompts/sc-02.txt"
    run_test "CA-02" "Registry Agent report template" "prompts/ca-02.txt"
fi

# Summary
cat >> "$RESULTS_FILE" << EOF

## Summary

| Test | Score | Notes |
|------|-------|-------|
| Total | -/10 | Pending execution |

---

*Generated by run-test-protocol.sh*
EOF

echo "================================"
echo "Results file created: $RESULTS_FILE"
echo ""
echo "Next steps:"
echo "1. Open Claude Code in this directory"
echo "2. Run each test prompt from docs/test-protocol-full-stack.md"
echo "3. Fill in results in $RESULTS_FILE"
echo "================================"
